In [1]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([[1, 6], [2, 8], [3, 11], [3, 10], [1, 7]])
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [4]:
mean_a = a.mean(axis=0)
mean_a

array([2. , 8.4])

In [5]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [8]:
v1 = a_centered[:, 0]
v2 = a_centered[:, 1]
a_centered_sp = v1 @ v2
a_centered_sp

8.0

In [9]:
n = a_centered_sp / 4
n

2.0

In [10]:
a_trans = a.transpose()
a_cov = np.cov(a_trans)
a_cov

array([[1. , 2. ],
       [2. , 4.3]])

In [31]:
authors = pd.DataFrame({'author_id': [1, 2, 3], 'author_name': ['Тургенев', 'Чехов', 'Островский']})
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [32]:
book = pd.DataFrame({'author_id': [1, 1, 1, 2, 2, 3, 3], 'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 'price': [450, 300, 350, 500, 450, 370, 290]})
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [33]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [34]:
top5 = authors_price.nlargest(5, 'price')
top5

author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350

In [35]:
minp = authors_price.groupby('author_name').agg({'price': 'min'})
maxp = authors_price.groupby('author_name').agg({'price': 'max'})
meanp = authors_price.groupby('author_name').agg({'price': 'mean'})

authors_stat = pd.concat([minp, maxp, meanp], axis=1)
authors_stat

price  price       price
author_name                          
Островский     290    370  330.000000
Тургенев       300    450  366.666667
Чехов          450    500  475.000000

In [39]:
cov = pd.DataFrame({'cover': ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']})
authors_price = pd.concat([authors_price, cov], axis = 1)
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [42]:
?pd.pivot_table

In [45]:
book_info = pd.pivot_table(authors_price, values='price', index='author_name', columns='cover', aggfunc=sum, fill_value = 0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950